services:
  frontend:
    image: agent-openai-banking-assistant-csharp/frontend
    build: ./frontend
    environment:
      REACT_APP_API_BASE_URL: "http://bankingassistant:8080"
    ports:
      - "80:80"
  bankingassistant:
    image: agent-openai-banking-assistant-csharp/banking-assistant
    build: ./banking-assistant
    environment:
      - DOTNET_Storage__AccountName=${AZURE_STORAGE_ACCOUNT}
      - DOTNET_Storage__ContainerName=${AZURE_STORAGE_CONTAINER}
      - DOTNET_AzureOpenAI__Endpoint=${AZURE_OPENAI_ENDPOINT}
      - DOTNET_AzureOpenAI__Deployment=${AZURE_OPENAI_CHATGPT_DEPLOYMENT}
      - DOTNET_AzureOpenAI__ApiKey=${AZURE_OPENAI_APIKEY}
      - DOTNET_DocumentIntelligence__ApiKey=${AZURE_DOCUMENT_INTELLIGENCE_SERVICE_APIKEY}
      - DOTNET_DocumentIntelligence__Endpoint=${AZURE_DOCUMENT_INTELLIGENCE_SERVICE_ENDPOINT}
      - DOTNET_BackendAPIs__AccountsApiUrl=http://account:8080
      - DOTNET_BackendAPIs__PaymentsApiUrl=http://payment:8080
      - DOTNET_BackendAPIs__TransactionsApiUrl=http://transaction:8080
      - DOTNET_AzureAd__ClientId=${servicePrincipal}
      - DOTNET_AzureAd__TenantId=${servicePrincipalTenant}
      - DOTNET_ApplicationInsights__Active=false
      - AZURE_CLIENT_ID=${servicePrincipal}
      - AZURE_TENANT_ID=${servicePrincipalTenant}
      - AZURE_CLIENT_SECRET=${servicePrincipalPassword}

  account:
    image: agent-openai-banking-assistant-csharp/business-account-mcp
    build:
      context: ./business-api/account-mcp
  payment:
    image: agent-openai-banking-assistant-csharp/business-payment-mcp
    build:
      context: ./business-api/payment-mcp
    environment:
      - DOTNET_BackendAPIs__TransactionsApiUrl=http://transaction:8080
  transaction:
    image: agent-openai-banking-assistant-csharp/business-transaction-api
    build:
      context: ./business-api/transactions-api


