version: '3.8'

services:
  # Payments Service
  payment-api:
    build:
      context: ./payment-api
    container_name: payment-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - business-api-network

  # Transactions Service  
  transactions-api:
    build:
      context: ./transactions-api
    container_name: transactions-api
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - business-api-network

  # Additional Service (generic placeholder)
  account-api:
    build:
      context: ./account-api
    container_name: account-api
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - business-api-network

# Network configuration
networks:
  business-api-network:
    driver: bridge

# Optional volume for persistent data
volumes:
  business-data:
    driver: local